name: Deploy to Hugging Face Spaces
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{secrets.HF_TOKEN }}
          HFUSER: ${{secrets.DOCKER_USERNAME }}
        run: git remote add space https://$HFUSER:$HF@huggingface.co/spaces/$HFUSER/Robust_RGB-D_Saliency_Detection
      - name: Push to hub
        env:
          HF: ${{ secrets.HF_TOKEN}}
          HFUSER: ${{secrets.DOCKER_USERNAME }}
        run: git push --force https://$HFUSER:$HF@huggingface.co/spaces/$HFUSER/Robust_RGB-D_Saliency_Detection main